from __future__ import annotations

SUPERVISOR_AGENT = "SuperVisorAgent"
INTAKE_AGENT = "IntakeAgent"
LOG_ANALYZER_AGENT = "LogAnalyzerAgent"
KNOWLEDGE_RETRIEVER_AGENT = "KnowledgeRetrieverAgent"
RESOLUTION_AGENT = "ResolutionAgent"
DRAFT_WRITER_AGENT = "DraftWriterAgent"
COMPLIANCE_REVIEWER_AGENT = "ComplianceReviewerAgent"
APPROVAL_AGENT = "ApprovalAgent"
TICKET_UPDATE_AGENT = "TicketUpdateAgent"

DEFAULT_AGENT_ROLES: tuple[str, ...] = (
    SUPERVISOR_AGENT,
    INTAKE_AGENT,
    LOG_ANALYZER_AGENT,
    KNOWLEDGE_RETRIEVER_AGENT,
    RESOLUTION_AGENT,
    DRAFT_WRITER_AGENT,
    COMPLIANCE_REVIEWER_AGENT,
)