from __future__ import annotations

SUPERVISOR_AGENT = "SuperVisorAgent"
OBJECTIVE_EVALUATION_AGENT = "ObjectiveEvaluationAgent"
INTAKE_AGENT = "IntakeAgent"
INVESTIGATE_AGENT = "InvestigateAgent"
LOG_ANALYZER_AGENT = "LogAnalyzerAgent"
KNOWLEDGE_RETRIEVER_AGENT = "KnowledgeRetrieverAgent"
DRAFT_WRITER_AGENT = "DraftWriterAgent"
BACK_SUPPORT_ESCALATION_AGENT = "BackSupportEscalationAgent"
BACK_SUPPORT_INQUIRY_WRITER_AGENT = "BackSupportInquiryWriterAgent"
APPROVAL_AGENT = "ApprovalAgent"
TICKET_UPDATE_AGENT = "TicketUpdateAgent"

DEFAULT_AGENT_ROLES: tuple[str, ...] = (
    SUPERVISOR_AGENT,
    OBJECTIVE_EVALUATION_AGENT,
    INTAKE_AGENT,
    INVESTIGATE_AGENT,
    LOG_ANALYZER_AGENT,
    KNOWLEDGE_RETRIEVER_AGENT,
    DRAFT_WRITER_AGENT,
    BACK_SUPPORT_ESCALATION_AGENT,
    BACK_SUPPORT_INQUIRY_WRITER_AGENT,
    APPROVAL_AGENT,
    TICKET_UPDATE_AGENT,
)